import { Navbar } from "@repo/ui/navbar";

import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const user = "jvrjvl";

const navContent = user
  ? [
      { item: "Requested Items", link: "/" },
      { item: "Create Listing", link: "/" },
    ]
  : [];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar navItems={navContent} user={user} />

        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
