version: "3.8"

services:
  api:
    restart: always
    build:
      target: "dev"
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: "postgresql://postgres:supersecret@db:5432/collegebaydb?schema=public"
      REDIS_URL: "redis://redis:6379"
      SECRET: "supersecret123@#"
      SEAL_PASSWORD: "cyz7:~WY^p?8kXDgQ9r,yPTt94~tt0*Pk^]Ne2"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "supersecret"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
